### PR TITLE
fix for issue #56

### PR DESCRIPTION
**Pull request by yinwang0**

### CODE REVIEW

**Comment by michaelficarra** [comment]
This is far too simplistic of a fix. We should ignore only the potentially problematic locations, and only if a flag is enabled.

**Comment by yinwang0** [comment]
It is simple because an ideal language won't allow any single-statement blocks without braces. It's just confusing. Removing the braces can't make the code much shorter.

**Comment by michaelficarra** [comment]
We're not talking about an ideal language here. What is the size difference for AngularJS with/without the braces?

**Comment by yinwang0** [comment]
The size difference is up to you to find out. I offered all I'd like to help.

**Pull request closed without merging**
