### PR TITLE
Es2017

### PR DESCRIPTION
**Pull request by alippai**
This should add async support to shift-java.
I didn't write Java or parser before, any guidance or fixes are welcomed :)

### CODE REVIEW

**Comment by alippai** [comment]
The async function declaration somewhat works, I don't think the reported errors are good. AwaitExpression is still buggy (it confuses await for identifier instead of a keyword)
Async methods, default parameters etc are missing

**Comment by alippai** [comment]
Fixed async methods, however there are two errors I can't figure out now:
> Failed tests: 
>   CodeGenTest.testAwaitExpression:126->test:74->lambda$test$0:75 Location for FunctionDeclaration should be the same according to the parser and the code generator expected:<com.shapesecurity.functional.data.Maybe@f0ffbab7> but was:<com.shapesecurity.functional.data.Maybe@c7669e7a>

It must be something async function vs function locations.

> Tests in error: 
>   ReducerTest.testLibraryCounter:120->countLibrary:41 » Js JavaScript error: Lin...

This could be something with the async/await as identifier thing or error handling problem.

**Comment by bakkot** [comment]
> It must be something async function vs function locations.

Yeah, looks like the parser isn't considering the `async` token to be part of the location information, whereas the codegen is. (I just pushed a commit to your branch to make the error message less opaque.)

It should be included. This is probably just a matter of moving `startState = this.startNode()` above wherever you're eating `async`.

**Comment by bakkot** [comment]
> This could be something with the async/await as identifier thing or error handling problem.

Looking around the line reported in the error message:

```js
jQuery.ajax({
  url: node.src,
  type: "GET",
  dataType: "script",
  async: false,
  global: false,
  "throws": true
});
```

Looks like your change breaks `async` as a key in an object. That's still legal, so that's a bug, somewhere.

**Comment by alippai** [comment]
Yay, thanks for the awesome help! Now more tests are passing (on Java9 too). How should I proceed?

**Comment by alippai** [comment]
I completely forgot async arrows... 🙄 
That's the next then.

**Comment by alippai** [comment]
Any ideas how should I add await support to the async arrows? Do you think splitting the async part (commit 0078b9d) is a good idea?

**Comment by bakkot** [comment]
Superseded by #217.

**Pull request closed without merging**
