### PR TITLE
Properly codegen null byte in string literal

### LINKED ISSUE #109: Codegen for LiteralStringExpression will sometimes gives wrong result
`"\u00005"`, which is `"\0" +  "5"`, is generated as `"\05"`, which is a single character.

### PR DESCRIPTION
**Pull request by ikarienator**
Fixes #109.

### CODE REVIEW

**Comment by michaelficarra** [comment]
This is not minimal. :-1: Let's do it right.

**Comment by ikarienator** [comment]
@michaelficarra being minimal is not a requirement. Please read README.md.

**Comment by michaelficarra** [comment]
LGTM now.

**Comment by ikarienator** [comment]
LGTM.

**Pull request merged**
