### PR TITLE
Es6 early errors

### PR DESCRIPTION
**Pull request by bakkot**

### CODE REVIEW

**Comment by michaelficarra** [comment]
I've rebased for you so that it will merge properly, but CI is failing:

```
Results :
Failed tests: 
  EarlyErrorsTest.testEarlyTokenizationErrors:78->ParserTestCase.testScriptFailure:77->ParserTestCase.testScriptFailureML:69 expected:<0> but was:<6>
  EarlyErrorsTest.testEarlyGrammarErrors:11->ParserTestCase.testScriptFailure:77->ParserTestCase.testScriptFailureML:69 expected:<0> but was:<3>
Tests run: 347, Failures: 2, Errors: 0, Skipped: 0
```

Looks like you were only running `testEarlyErrors`.

**Comment by bakkot** [comment]
Yup. Diidn't update the indices yet. I'll get on that.

**Comment by bakkot** [comment]
Done. Two of them (see below) are actually making it through the parser, incorrectly. Should I comment them out for now, or what? I'm not sure how to fix them.

``` java
testScriptFailure("a\\u0000", 0, "Unexpected end of input"); // TODO this should error
testScriptFailure("a\\u{0}", 0, "Unexpected end of input"); // TODO this should error
```

**Comment by michaelficarra** [comment]
Comment them out, open an issue, I'll fix the parser. Ready to merge otherwise? I will look into the possible import specifier bug.

**Comment by bakkot** [comment]
Commented out. And yes, ready to merge, although MultiHashTable is still in entirely the wrong place (ie EarlyErrorState.java) - are we OK with putting it in functional without being particularly documented?

**Comment by bakkot** [comment]
Also, EarlyErrorChecker is not yet being used by default in the parser.

**Comment by michaelficarra** [comment]
Oh yes, move that. And we don't want it used by default in this implementation.

**Comment by bakkot** [comment]
Moved.

**Comment by michaelficarra** [comment]
I looked into ImportSpecifier: it's not needed, since ImportSpecifier contains BindingIdentifier for the parts that actually declare bindings.

**Pull request merged**
